//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHubRepoList {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitHubRepoList.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE GetRepos
        ///	-- AUTHENTICATION DETAILS
        ///	@login		VARCHAR(MAX),
        ///	@password	VARCHAR(MAX)
        ///	-- END OF AUTHENTICATION DETAILS
        ///AS
        ///BEGIN
        ///	IF EXISTS (SELECT * FROM Users WHERE [login] = @login AND [password] = @password AND ([is_read] = &apos;True&apos; OR [is_admin] = &apos;True&apos;))
        ///	BEGIN
        ///		SELECT * FROM Repoes
        ///	END
        ///	ELSE
        ///	BEGIN
        ///		RAISERROR (&apos;Insufficient privileges!&apos;, 11, 1)
        ///	END
        ///END
        ///GO
        ///
        ///CREATE PROCEDURE CreateRepo
        ///	@name			NVARCHAR(MAX),
        ///	@full_name		NVARCHAR(MAX),
        ///	@description	NVARCHAR(MAX), [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_RepoCrud {
            get {
                return ResourceManager.GetString("Create_sp_RepoCrud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE AuthUser
        ///	-- AUTHENTICATION DETAILS
        ///	@login		VARCHAR(MAX),
        ///	@password	VARCHAR(MAX)
        ///	-- END OF AUTHENTICATION DETAILS
        ///AS
        ///BEGIN
        ///	SELECT * FROM Users WHERE [login] = @login AND [password] = @password
        ///END
        ///GO
        ///
        ///CREATE PROCEDURE GetUsers
        ///	-- AUTHENTICATION DETAILS
        ///	@login		VARCHAR(MAX),
        ///	@password	VARCHAR(MAX)
        ///	-- END OF AUTHENTICATION DETAILS
        ///AS
        ///BEGIN
        ///	IF EXISTS (SELECT * FROM Users WHERE [login] = @login AND [password] = @password AND [is_admin] = &apos;True&apos;)
        ///	BEGIN
        ///		SELECT * FR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_UserOps {
            get {
                return ResourceManager.GetString("Create_sp_UserOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limited.
        /// </summary>
        internal static string DefaultAuthHeaderLogin {
            get {
                return ResourceManager.GetString("DefaultAuthHeaderLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limited.
        /// </summary>
        internal static string DefaultAuthHeaderPassword {
            get {
                return ResourceManager.GetString("DefaultAuthHeaderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PROCEDURE GetRepos
        ///DROP PROCEDURE CreateRepo
        ///DROP PROCEDURE UpdateRepo
        ///DROP PROCEDURE DeleteRepo
        ///.
        /// </summary>
        internal static string Drop_sp_RepoCrud {
            get {
                return ResourceManager.GetString("Drop_sp_RepoCrud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PROCEDURE AuthUser
        ///DROP PROCEDURE GetUsers
        ///DROP PROCEDURE UpdateUser.
        /// </summary>
        internal static string Drop_sp_UserOps {
            get {
                return ResourceManager.GetString("Drop_sp_UserOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.github.com/users/{0}/repos.
        /// </summary>
        internal static string GitHubApiListReposUrl {
            get {
                return ResourceManager.GetString("GitHubApiListReposUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; .NET CLR 1.0.3705;).
        /// </summary>
        internal static string WebClientUserAgent {
            get {
                return ResourceManager.GetString("WebClientUserAgent", resourceCulture);
            }
        }
    }
}
