// <auto-generated />
namespace GitHubRepoList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_sp_UserOps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_sp_UserOps));
        
        string IMigrationMetadata.Id
        {
            get { return "201706161406397_add_sp_UserOps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
